# Site settings
title: Mihai Valentin
description: "Mihai Valentin - Software Engineer with a strong focus on Front-end technologies (Angular, JavaScript, HTML5)"
baseurl: ""
url: "https://www.mihaivalentin.com"
disqus_shortname: mihaivalentin
twitter_username: mihai_valentin
github_username:  MihaiValentin
linkedin_username: mihaivalentin
safe: false

# Build settings
markdown: kramdown
permalink: /:title/

gems:
  - jekyll-redirect-from